
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.jiang.entities
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
  application:
    name: microservicecloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://172.20.68.236\MSSQLSERVER2017:54451;database=SD_PKG_20191212
    username: sa
    password: 123456
server:
  port: 8001

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: microservicecloud-dept8001
    prefer-ip-address: true

info:
  app.name: jiang-microservicecloud
  company.name: www.jiang.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$